export default [
    {
        id: 0,
        img: "/product__1.png",
        name: "Wild Slik Lipstick",
        price: 380,
        category: ["lipsticks"],
        sale: false,
    },
    {
        id: 1,
        img: "/product__2.png",
        name: "Wild Slik Lipstick",
        price: 380,
        category: ["lipsticks"],
        sale: false,
    },
    {
        id: 2,
        img: "/product__3.png",
        name: "Wild Slik Lipstick",
        price: 380,
        category: ["lipsticks"],
        sale: false,
    },
    {
        id: 3,
        img: "/product__4.png",
        name: "Wild Slik Lipstick",
        price: 380,
        category: ["lipsticks", "makeup"],
        sale: true,
    },
    {
        id: 4,
        img: "/product__5.png",
        name: "Wild Slik Lipstick",
        price: 380,
        category: ["skin care"],
        sale: false,
    },
]